balboa:
    target: dev
    outputs:
      dev:
        type: snowflake
        account: "toa80779"
        user: "svc_balboa"
        role: ANALYST
        password: "5Vc_C0nvexa_b@Lb0A"
        database: "BALBOA"
        warehouse: TRANSFORMING_WAREHOUSE
        schema: dev
        threads: 8
        keepalives_idle: 0 

snow_test:
    target: dev
    outputs:
      dev:
        type: snowflake
        account: "xoa93964"
        user: "bantonellini"
        role: SYSADMIN
        password: "Bruno@c0nvexa"
        database: TEST
        warehouse: COMPUTE_WH
        schema: dev
        threads: 8
        keepalives_idle: 0 