balboa:
    target: dev
    outputs:
      dev:
        type: snowflake
        account: "{{ env_var('DBT_ACCOUNT') }}"
        user: "{{ env_var('DBT_USER') }}"
        role: ANALYST
        password: "{{ env_var('DBT_PASSWORD') }}"
        database: "{{ env_var('DBT_DATABASE') }}"
        warehouse: TRANSFORMING_WAREHOUSE
        schema: dev
        threads: 8
        keepalives_idle: 0 # default 0, indicating the system default
